### ISSUE TITLE
FocusLost not triggered in firenvim

### ISSUE THREAD

**Issue by NilsIrl** [Julian/dotfiles#59]
I have added the following lines to my configs:

https://github.com/Julian/dotfiles/blob/39fabf39f7633162e121f2fa605b9910bee76419/.config/nvim/firen.vim#L16-L17

but it doesn't work for me. Can you confirm that either this works or is a regression in Firenvim?

follow up to: https://github.com/glacambre/firenvim/issues/117#issuecomment-572264657

**Comment by Julian** [comment]
Hey!

Uh, it was working as of a month or so ago, but I haven't actually used firenvim in a while -- I'll come back to it someday, but I had to disable it since I got tired of managing turning it off for too many places where it was misdetecting the sizes of elements (in particular it got really annoying when using Asana)...

So yeah don't know unfortunately whether it's stopped working for auto-save.
